[project]
authors = ["dotnethero <andrii.horbokon@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "philox-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
cpu = "mojo run playground.mojo"
gpu = "mojo run playground-gpu.mojo"
test = "mojo test"

[dependencies]
max = ">=25.3.0.dev2025042405,<26"
